# Generated by Django 5.2.11 on 2026-03-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicrequest',
            name='evidence_dir',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
