
# Centralized Prompts for Forensic Analysis

PROMPTS = {
    "visual_analysis": {
        "default": (
            "Analyze this forensic mask generated by the '{model_name}' model (Frame {idx}). "
            "White areas typically indicate manipulation. What does this mask show?"
        ),
        "trufor": (
            "Analyze this TruFor localization mask (Frame {idx}). "
            "The white pixels represent high probability of image forgery/manipulation. "
            "Describe the shape, size, and location of the white regions. "
            "Do they correspond to a face, a specific object, or the background?"
        ),
        "edgedoc": (
            "Analyze this EdgeDoc edge-inconsistency heatmap (Frame {idx}). "
            "Bright areas suggest boundaries where splicing or manipulation might have occurred. "
            "Is there a clear anomalous edge?"
        ),
        "gradcam": (
            "Analyze this Grad-CAM heatmap from the '{model_name}' model (Frame {idx}). "
            "The red/hot areas show where the model focused to make its decision. "
            "Does the model focus on facial features (eyes, mouth) or irrelevant background artifacts?"
        )
    },
    "final_report": (
        "You are a Senior Digital Forensics Expert at a top-tier security firm. "
        "Your task is to analyze the following technical results from a suite of detection models "
        "and write a formal, authoritative report for a client.\n\n"
        "### Context: Model Stages Included in Analysis\n"
        "{stages_context}\n\n"
        "### 1. Global Model Scores\n"
        "{data_json}\n\n"
        "### 2. Visual Evidence Analysis\n"
        "(You previously analyzed specific masks/heatmaps. Here is a summary of your findings:)\n"
        "{visual_summary}\n\n"
        "### Instructions\n"
        "- Synthesize the numerical scores and visual analysis into a coherent narrative, grouping findings by the stages above.\n"
        "- Explain discrepancies if models disagree (e.g., if Stage 1 says Real but Stage 2 shows a clear mask).\n"
        "- Provide a **Final Verdict**: REAL or FAKE.\n"
        "- Assign a confidence score (0-100%).\n"
        "- Write a **detailed report ONLY for the models listed above**. Do not invent results for missing stages.\n" 
        "- Conclude with specific recommendations for the client."
    )
}
