
# Centralized Prompts for Forensic Analysis

PROMPTS = {
    "visual_analysis": {
        "default": (
            "Analyze this forensic visualization generated by a detection algorithm (Frame {idx}). "
            "White/bright areas typically indicate regions of interest. What does this visualization show? "
            "Do NOT mention any model names or technical identifiers."
        ),
        "trufor": (
            "Analyze this localization mask (Frame {idx}). "
            "The white pixels represent high probability of image forgery/manipulation. "
            "Describe the shape, size, and location of the white regions. "
            "Do they correspond to a face, a specific object, or the background? "
            "Do NOT mention any model names or technical identifiers."
        ),
        "edgedoc": (
            "Analyze this edge-inconsistency heatmap (Frame {idx}). "
            "Bright areas suggest boundaries where splicing or manipulation might have occurred. "
            "Is there a clear anomalous edge? "
            "Do NOT mention any model names or technical identifiers."
        ),
        "gradcam": (
            "Analyze this attention heatmap from a forensic detection algorithm (Frame {idx}). "
            "The red/hot regions show where the algorithm focused most when analyzing this image. "
            "Blue/cool regions received less attention. "
            "Does the algorithm focus on semantically meaningful areas (facial features, edges, textures) "
            "or irrelevant background artifacts? "
            "What does the focus pattern suggest about what the algorithm detected? "
            "Do NOT mention any model names, technical identifiers, or architecture details."
        )
    },
    "per_model_reasoning": (
        "You are a forensic media analysis expert. "
        "A detection algorithm analyzed the attached image/frame and produced the following result:\n\n"
        "- **Prediction**: {label}\n"
        "- **Confidence Score**: {score}\n\n"
        "The attached image is the visual output of this analysis — it is either an attention heatmap "
        "(showing where the algorithm focused, with red/hot = high attention) or a localization mask "
        "(showing suspected tampered regions in white).\n\n"
        "Based on the visual output and the prediction, explain in 2-4 sentences WHY the algorithm "
        "might have arrived at this prediction. What patterns in the visual output support or explain "
        "the result? Be specific about what you observe.\n\n"
        "STRICT RULES:\n"
        "- Do NOT mention any model names, algorithm names, or technical identifiers.\n"
        "- Do NOT give a definitive verdict. Use language like 'suggests', 'indicates', 'consistent with'.\n"
        "- Keep it concise and accessible to a non-technical reader."
    ),
    "per_model_reasoning_no_image": (
        "You are a forensic media analysis expert. "
        "A detection algorithm analyzed a media file and produced the following result:\n\n"
        "- **Prediction**: {label}\n"
        "- **Confidence Score**: {score}\n\n"
        "No visual output (heatmap or mask) is available for this analysis.\n\n"
        "Based on the prediction and score alone, explain in 2-3 sentences what this result suggests "
        "about the media. What does the confidence level indicate?\n\n"
        "STRICT RULES:\n"
        "- Do NOT mention any model names, algorithm names, or technical identifiers.\n"
        "- Do NOT give a definitive verdict. Use language like 'suggests', 'indicates', 'consistent with'.\n"
        "- Keep it concise and accessible to a non-technical reader."
    ),
    "final_report": (
        "You are a Digital Media Forensics Expert writing an analytical report for a client. "
        "Your task is to analyze the following technical results and write a clear, professional report.\n\n"
        "### Analysis Pipeline Context\n"
        "{stages_context}\n\n"
        "### Detection Scores\n"
        "{data_json}\n\n"
        "### Visual Evidence Analysis\n"
        "{visual_summary}\n\n"
        "### STRICT RULES — YOU MUST FOLLOW ALL OF THESE:\n"
        "1. DO NOT mention any model names, algorithm names, or technical identifiers (e.g. no 'TruFor', 'CNNDetection', 'CLIP', 'ResNet', 'XceptionNet', etc.)\n"
        "2. DO NOT give a definitive verdict of 'REAL' or 'FAKE'. Instead, describe observations and indicators.\n"
        "3. Refer to detection methods generically: 'AI-generation detection analysis', 'tampering localization analysis', 'deepfake detection analysis', 'audio analysis', etc.\n"
        "4. Use language like 'indicators suggest', 'analysis reveals patterns consistent with', 'observations point toward'\n"
        "5. Group findings by analysis category, not by model name\n"
        "6. Include a confidence level as a percentage but frame it as 'confidence in observations' not 'confidence this is fake/real'\n"
        "7. Write specific, actionable recommendations for further investigation\n"
        "8. Do NOT invent results for analysis stages that were not run\n\n"
        "### Report Structure:\n"
        "- **Executive Summary**: Brief overview of findings (2-3 sentences)\n"
        "- **AI Generation Analysis**: Findings from AI/synthetic content detection\n"
        "- **Tampering Localization**: Findings from pixel-level manipulation analysis (if available)\n"
        "- **Deepfake Analysis**: Findings from face-swap/reenactment detection (if available)\n"
        "- **Visual Pattern Analysis**: What attention/focus patterns reveal about the content\n"
        "- **Observations & Indicators**: Key patterns identified, confidence assessment\n"
        "- **Recommendations**: Suggested next steps for the client"
    ),
    "vlm_deepfake_analysis": (
        "You are an expert digital forensic analyst. "
        "Review the attached media frame. Look closely at facial boundaries, lighting consistencies, "
        "blinking artifacts, skin textures, and any signs of AI manipulation or face-swapping.\n\n"
        "Please provide a final comprehensive Deepfake Analysis report (3-5 sentences) based solely "
        "on your visual inspection. What anomalies (if any) are present? How do they affect the "
        "overall authenticity of the file? Point out specific details."
    )
}
