import os
import requests
import json
import logging
import base64
from pathlib import Path
from .interfaces import ReportGeneratorInterface

from .prompts import PROMPTS

logger = logging.getLogger(__name__)

class DeepSeekReportGenerator(ReportGeneratorInterface):
    def __init__(self):
        self.api_key = os.getenv("OLLAMA_API_KEY")
        self.api_url = os.getenv("OLLAMA_API_URL")
        # Default to qwen3-vl if not set
        self.model_name = os.getenv("OLLAMA_MODEL", "qwen3-vl") # Corrected model name default
        
    def _encode_image(self, image_path):
        try:
            with open(image_path, "rb") as image_file:
                return base64.b64encode(image_file.read()).decode('utf-8')
        except Exception as e:
            logger.error(f"Failed to encode image {image_path}: {e}")
            return None

    def _call_ollama(self, prompt, images=None):
        if not self.api_url:
            return "Configuration Error: OLLAMA_API_URL not set."

        headers = {
            "Content-Type": "application/json"
        }
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"

        request_data = {
            "model": self.model_name,
            "prompt": prompt,
            "stream": False
        }
        
        if images:
            request_data["images"] = images

        try:
            response = requests.post(self.api_url, headers=headers, json=request_data, timeout=120)
            response.raise_for_status()
            result = response.json()
            return result.get('response', 'No response field in output.')
        except Exception as e:
            logger.error(f"Error calling API: {e}")
            return f"Error: {str(e)}"

    def generate(self, data: dict, input_path: str = None) -> str:
        
        # 1. Sequential Analysis of Visual Artifacts (Masks/GradCAMs)
        visual_analysis_report = []
        
        if input_path:
            input_dir = os.path.dirname(os.path.abspath(input_path))
            
            for model_name, result in data.items():
                if not isinstance(result, dict): continue
                
                details = result.get('details', {})
                # Check for masks
                masks = details.get('masks', [])
                if masks:
                    # masks might be a list of filenames or None
                    for idx, mask_file in enumerate(masks):
                        if not mask_file: continue
                        
                        mask_path = os.path.join(input_dir, mask_file)
                        if os.path.exists(mask_path):
                            encoded_mask = self._encode_image(mask_path)
                            if encoded_mask:
                                # Get specific prompt or default
                                prompt_template = PROMPTS["visual_analysis"].get(
                                    model_name, 
                                    PROMPTS["visual_analysis"]["default"]
                                )
                                prompt = prompt_template.format(model_name=model_name, idx=idx)
                                
                                analysis = self._call_ollama(prompt, images=[encoded_mask])
                                visual_analysis_report.append(f"**{model_name} Mask Analysis (Frame {idx})**:\n{analysis}")

        # 2. Final Comprehensive Report
        visual_summary = "\n\n".join(visual_analysis_report) if visual_analysis_report else "No visual artifacts (masks/heatmaps) were detected/generated by the selected models."
        
        final_prompt = PROMPTS["final_report"].format(
            data_json=json.dumps(data, indent=2),
            visual_summary=visual_summary
        )
        
        return self._call_ollama(final_prompt)

class RemoteOllamaReportGenerator(ReportGeneratorInterface):
    def __init__(self):
        # We are bypassing .env entirely because the environment runner (start.sh/celery) 
        # is holding onto old stuck variables (deepseek-r1, /ollama/api/generate)
        self.api_key = "sk-1550d490e41a4fefa8ba15ba14790454"
        self.api_url = "http://10.4.16.84:9000/api/chat/completions"
        self.model_name = "qwen3-vl:latest"
        
        logger.info(f"Initialized RemoteOllamaReportGenerator with model: {self.model_name} at {self.api_url}")

    def _encode_image(self, image_path):
        try:
            with open(image_path, "rb") as image_file:
                return base64.b64encode(image_file.read()).decode('utf-8')
        except Exception as e:
            logger.error(f"Failed to encode image {image_path}: {e}")
            return None

    def _generate_markdown_table(self, data: dict) -> str:
        """Generates a Markdown table for model results."""
        table = "| Model | Score | Prediction | Status |\n"
        table += "| :--- | :---: | :---: | :--- |\n"
        
        for model_name, result in data.items():
            if isinstance(result, str):
                try:
                    result = json.loads(result)
                except json.JSONDecodeError:
                    continue
            if not isinstance(result, dict): continue
            
            score = result.get('score', 'N/A')
            # Handle float scores formatting
            if isinstance(score, (float, int)):
                score_str = f"{score:.4f}"
            else:
                score_str = str(score)
                
            label = result.get('label', 'Unknown')
            
            table += f"| **{model_name.upper()}** | {score_str} | {label} | ✅ Success |\n"
            
        return table

    def _call_api_stream(self, messages: list) -> str:
        """Helper to call the remote (OpenAI-compatible) API and stream output."""
        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"
            
        payload = {
            "model": self.model_name,
            "messages": messages,
            "stream": True,
            "temperature": 0.2 # Lower temperature for stable reporting
        }
        
        output_text = ""
        try:
            response = requests.post(self.api_url, headers=headers, json=payload, stream=True, timeout=120)
            response.raise_for_status()
            
            for line in response.iter_lines():
                if line:
                    line = line.decode('utf-8')
                    if line.startswith("data: "):
                        line = line[6:]
                    if line == "[DONE]":
                        break
                    try:
                        json_data = json.loads(line)
                        delta = json_data.get("choices", [{}])[0].get("delta", {})
                        if "content" in delta:
                            content = delta["content"]
                            output_text += content
                    except json.JSONDecodeError:
                        pass
        except Exception as e:
            logger.error(f"Error calling remote API: {e}")
            return f"\n[API Error: {str(e)}]"
            
        return output_text

    def generate(self, data: dict, input_path: str = None) -> str:
        logger.info("🧠 [VLM] Starting remote report generation...")
        
        # 1. FIXED STRUCTURE: Data Table
        report_parts = []
        report_parts.append("# Forensic Analysis Report\n")
        report_parts.append("### 1. Model Results Summary\n")
        report_parts.append(self._generate_markdown_table(data))
        report_parts.append("\n---\n")

        # 2. VLM ANALYIS: Visuals
        report_parts.append("### 2. Visual Evidence Analysis\n")
        
        # Define Stage Mapping
        MODEL_STAGES = {
            "univfd": "Stage 1 (AI/Fake Detection): General purpose detectors identifying if content is AI-generated.",
            "rine": "Stage 1 (AI/Fake Detection): Robust AI-generated image detection.",
            "trufor": "Stage 2 (Tampering Localization): Pinpoints specific manipulated regions (splicing/inpainting).",
            "deepfake_bench": "Stage 3 (Deepfake Detection): Specialized face-swap and reenactment detection.",
            "rawnet": "Stage 4 (Audio Spoofing): Detects synthetic or cloned audio.",
            "edgedoc": "Stage 5 (Document Tampering): Analyzes structure and edges in documents."
        }
        
        # Generate Stages Context
        active_stages = []
        for model in data.keys():
            if model in MODEL_STAGES:
                active_stages.append(f"- **{model.upper()}** -> {MODEL_STAGES[model]}")
        
        stages_context = "\n".join(active_stages) if active_stages else "No specific forensic models were run."
        visual_analysis_text = []
        
        if input_path:
            input_dir = os.path.dirname(os.path.abspath(input_path))
            
            for model_name, result in data.items():
                if isinstance(result, str):
                    try:
                        result = json.loads(result)
                    except json.JSONDecodeError:
                        continue
                if not isinstance(result, dict): continue
                
                details = result.get('details', {})
                if isinstance(details, str):
                    try:
                        details = json.loads(details)
                    except json.JSONDecodeError:
                        details = {}
                if not isinstance(details, dict):
                    details = {}
                    
                masks = details.get('masks', [])
                if masks:
                    logger.info(f"🖼️  [VLM] Found {len(masks)} masks for model {model_name}")
                    for idx, mask_file in enumerate(masks):
                        if not mask_file: continue
                        
                        mask_path = os.path.join(input_dir, mask_file)
                        if os.path.exists(mask_path):
                            logger.info(f"👁️  [VLM] Analyzing mask: {mask_file}")
                            
                            encoded_mask = self._encode_image(mask_path)
                            if not encoded_mask:
                                continue
                                
                            prompt_template = PROMPTS["visual_analysis"].get(model_name, PROMPTS["visual_analysis"]["default"])
                            text_prompt = prompt_template.format(model_name=model_name, idx=idx)
                            
                            messages = [
                                {
                                    "role": "user",
                                    "content": [
                                        {"type": "text", "text": text_prompt},
                                        {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{encoded_mask}"}}
                                    ]
                                }
                            ]
                            
                            print(f"[{model_name}] Generating:", end=" ", flush=True)
                            analysis_output = self._call_api_stream(messages)
                            
                            # Add to report
                            image_markdown = f"![Analysis Mask](data:image/png;base64,{encoded_mask})"
                            report_parts.append(f"#### {model_name.upper()} Analysis (Frame {idx})\n{image_markdown}\n\n**VLM Observation**:\n{analysis_output}\n")
                            visual_analysis_text.append(f"Model {model_name} (Frame {idx}): {analysis_output}")

        if not visual_analysis_text:
            report_parts.append("**No specific visual artifacts identified.**\n")

        report_parts.append("\n---\n")

        # 3. LLM VERDICT
        report_parts.append("### 3. Comprehensive Verdict\n")
        logger.info("📝 [VLM] Generating final report summary...")
        
        visual_summary = "\n".join(visual_analysis_text) if visual_analysis_text else "No visual artifacts detected."
        
        final_prompt_text = PROMPTS["final_report"].format(
            stages_context=stages_context,
            data_json=json.dumps(data, indent=2),
            visual_summary=visual_summary
        )
        
        messages = [
            {"role": "user", "content": [{"type": "text", "text": final_prompt_text}]}
        ]
        
        print("[Final Report] Generating:", end=" ", flush=True)
        final_report = self._call_api_stream(messages)
        
        report_parts.append(final_report)
        logger.info("🏁 [VLM] Final report generated successfully.")
        
        return "\n".join(report_parts)
